### ISSUE TITLE
It's not possible to compile in the php:8.1-cli-alpine3.17

### ISSUE THREAD

**Issue by marko-ilic** [swoole/yasd#180]
It's not possible to compile yasd in the latest alpine PHP container `php:8.1-cli-alpine3.17`

Error message:

```
#0 27.83  g++ -I. -I/yasd -I/yasd/include -I/yasd/main -I/yasd -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/include -I/yasd/thirdparty/tinyxml2 -DHAVE_CONFIG_H -g -O2 -Wall -Wno-unused-function -Wno-deprecated -Wno-deprecated-declarations -std=c++11 -DZEND_COMPILE_DL_EXT=1 -c /yasd/src/remote_debugger.cc -MMD -MF src/remote_debugger.dep -MT src/remote_debugger.lo  -fPIC -DPIC -o src/.libs/remote_debugger.o
#0 32.41 In file included from /usr/local/include/php/main/php.h:255,
#0 32.41                  from ././php_yasd.h:20,
#0 32.41                  from ././php_yasd_cxx.h:3,
#0 32.41                  from /yasd/src/remote_debugger.cc:21:
#0 32.41 /usr/include/boost/assert/source_location.hpp: In member function 'std::string boost::source_location::to_string() const':
#0 32.41 /usr/local/include/php/main/snprintf.h:99:18: error: 'ap_php_snprintf' is not a member of 'std'; did you mean 'ap_php_snprintf'?
#0 32.41    99 | #define snprintf ap_php_snprintf
#0 32.41       |                  ^~~~~~~~~~~~~~~
#0 32.41 /usr/local/include/php/main/snprintf.h:74:12: note: 'ap_php_snprintf' declared here
#0 32.41    74 | PHPAPI int ap_php_snprintf(char *, size_t, const char *, ...) ZEND_ATTRIBUTE_FORMAT(printf, 3, 4);
#0 32.41       |            ^~~~~~~~~~~~~~~
#0 32.41 /usr/local/include/php/main/snprintf.h:99:18: error: 'ap_php_snprintf' is not a member of 'std'; did you mean 'ap_php_snprintf'?
#0 32.41    99 | #define snprintf ap_php_snprintf
#0 32.41       |                  ^~~~~~~~~~~~~~~
#0 32.41 /usr/local/include/php/main/snprintf.h:74:12: note: 'ap_php_snprintf' declared here
#0 32.41    74 | PHPAPI int ap_php_snprintf(char *, size_t, const char *, ...) ZEND_ATTRIBUTE_FORMAT(printf, 3, 4);
#0 32.41       |            ^~~~~~~~~~~~~~~
#0 32.96 make: *** [Makefile:253: src/remote_debugger.lo] Error 1
```

**Comment by magicento** [comment]
Any updates? thx. @marko-ilic
